### ISSUE TITLE
Automatically invalidate OTP token when detected

### ISSUE THREAD

**Issue by d0nutptr** [AndrewMohawk/yubisnooze#1]
I think a nice feature to add here would be to automatically invalidate the OTP token when it is detected. While probably unrealistic of an attack vector, one could grab the OTP token before yubisnooze edited it away and it would be valid until the yubikey or token is next used to authenticate.

The easy way to handle OTP invalidation would be to call Yubico's validation endpoint which will make the token invalid after that initial check. You could even collect reporting when that token seems to fail, for some reason (such as another script managing to grab + use the token ahead of yubisnooze's detection).

https://developers.yubico.com/OTP/Specifications/OTP_validation_protocol.html

**Comment by AndrewMohawk** [comment]
Updated this in the latest to invalidate the token and print to STDOUT :)
